# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_device_devicetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceType',
            field=models.CharField(choices=[('СТР', 'Стелка'), ('ЗАМ', 'Замедлитель'), ('ПЯ', 'Путевой ящик'), ('РИС', 'Измеритель скорости (РИС)')], max_length=5, verbose_name='Тип устройства'),
        ),
    ]
