# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20181213_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='deviceType',
            new_name='device_type',
        ),
        migrations.AlterField(
            model_name='device',
            name='factory_number',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Заводской номер'),
        ),
        migrations.AlterField(
            model_name='device',
            name='work_number',
            field=models.CharField(blank=True, max_length=5, verbose_name='Номер на поле'),
        ),
    ]
