# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20181213_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='state',
            field=models.CharField(choices=[('Установлен', 'Установлен'), ('Есть сбои', 'Есть сбои'), ('В запасе', 'В запасе')], default='В запасе', max_length=25, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('Стелка', 'Стелка'), ('Замедлитель', 'Замедлитель'), ('Путевой', 'Путевой ящик'), ('Измеритель скорости (РИС)', 'Измеритель скорости (РИС)')], max_length=25, verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='device',
            name='work_number',
            field=models.CharField(max_length=5, verbose_name='Номер на поле'),
        ),
        migrations.AlterField(
            model_name='work',
            name='deviceType',
            field=models.CharField(choices=[('Стелка', 'Стелка'), ('Замедлитель', 'Замедлитель'), ('Путевой', 'Путевой ящик'), ('Измеритель скорости (РИС)', 'Измеритель скорости (РИС)')], default='device', max_length=5, verbose_name='Тип устройства'),
        ),
    ]
