# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20181213_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата работы'),
        ),
        migrations.AddField(
            model_name='work',
            name='factory_number',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Заводской номер'),
        ),
        migrations.AddField(
            model_name='work',
            name='work_body',
            field=models.TextField(blank=True, null=True, verbose_name='Описание работы'),
        ),
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.CharField(choices=[('Есть сбои', 'Есть сбои'), ('Установлен', 'Установлен'), ('В запасе', 'В запасе')], default='В запасе', max_length=25, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='device',
            name='work_number',
            field=models.CharField(blank=True, max_length=5, verbose_name='Номер на поле'),
        ),
    ]
