# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-14 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20181213_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='work_station',
            field=models.CharField(choices=[('Нечетная', 'Нечетная'), ('Четная', 'Четная')], default='Четная', max_length=25, verbose_name='Станция установки'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('Стрелка', 'Стрелка'), ('Замедлитель', 'Замедлитель'), ('Путевой ящик', 'Путевой ящик'), ('Измеритель скорости (РИС)', 'Измеритель скорости (РИС)')], max_length=25, verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.CharField(choices=[('В запасе', 'В запасе'), ('Есть сбои', 'Есть сбои'), ('Установлен', 'Установлен')], default='В запасе', max_length=25, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='device',
            name='work_number',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Номер на поле'),
        ),
        migrations.AlterField(
            model_name='work',
            name='deviceType',
            field=models.CharField(choices=[('Стрелка', 'Стрелка'), ('Замедлитель', 'Замедлитель'), ('Путевой ящик', 'Путевой ящик'), ('Измеритель скорости (РИС)', 'Измеритель скорости (РИС)')], default='device', max_length=5, verbose_name='Тип устройства'),
        ),
    ]
