# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-19 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20181219_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.CharField(choices=[('Установлен', 'Установлен'), ('В запасе', 'В запасе'), ('Есть сбои', 'Есть сбои')], default='В запасе', max_length=25, verbose_name='Состояние'),
        ),
    ]
