# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-19 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20181219_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.CharField(choices=[('В запасе', 'В запасе'), ('Установлен', 'Установлен'), ('Есть сбои', 'Есть сбои')], default='В запасе', max_length=25, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='device',
            name='work_station',
            field=models.CharField(choices=[('Четная', 'Четная'), ('Нечетная', 'Нечетная')], default='Четная', max_length=25, verbose_name='Станция установки'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата работы'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_body',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание работы'),
        ),
    ]
